import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Service — Pantry",
  description: "Terms governing your use of the Pantry meal planning service.",
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-xl text-ink mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-muted leading-relaxed">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg">
      <header className="border-b border-line">
        <div className="container py-4 flex items-center justify-between">
          <Link href="/" className="font-display text-lg text-ink">Pantry</Link>
        </div>
      </header>

      <main className="container py-12 sm:py-16 max-w-2xl">
        <h1 className="font-display text-3xl sm:text-4xl text-ink mb-2">Terms of Service</h1>
        <p className="text-sm text-muted mb-10">Last updated: 23 June 2026</p>

        <Section title="1. Agreement">
          <p>
            By creating an account or using Pantry (&ldquo;the Service&rdquo;), you
            agree to these Terms of Service. If you do not agree, do not use the
            Service. These terms are governed by the laws of England and Wales.
          </p>
        </Section>

        <Section title="2. The Service">
          <p>
            Pantry is a meal planning tool that generates weekly meal plans, shopping
            lists, and budget estimates based on your preferences. The Service is
            provided &ldquo;as is&rdquo;. We do our best to make plans accurate and
            useful, but we do not guarantee that every recipe, price estimate, or
            nutritional figure is error-free.
          </p>
        </Section>

        <Section title="3. Accounts">
          <p>
            You must provide a valid email address to create an account. You are
            responsible for keeping your login credentials secure. One person per
            account — sharing login credentials is not permitted.
          </p>
          <p>
            We may suspend or terminate accounts that violate these terms or are
            used for abusive purposes (automated scraping, excessive API load, etc.).
          </p>
        </Section>

        <Section title="4. Free and Premium tiers">
          <p>
            Pantry offers a free tier and a paid Premium tier. The features included
            in each tier are described on our{" "}
            <Link href="/pricing" className="underline hover:text-ink">pricing page</Link>.
            We may change what is included in each tier with reasonable notice.
          </p>
        </Section>

        <Section title="5. Payments and cancellation">
          <p>
            Premium subscriptions are billed monthly or annually via Stripe. Prices
            are shown in GBP and include VAT where applicable.
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              You can cancel at any time through the billing portal. Cancellation
              takes effect at the end of the current billing period — there are no
              partial refunds for unused time.
            </li>
            <li>
              We may change prices with at least 30 days&rsquo; notice. Existing
              subscribers keep their current price until the end of their billing
              cycle, after which the new price applies.
            </li>
            <li>
              If payment fails, we will retry a few times and notify you. If payment
              cannot be collected, your account will revert to the free tier.
            </li>
          </ul>
        </Section>

        <Section title="6. Your content">
          <p>
            Any data you provide (preferences, household details, feedback) remains
            yours. We use it only to operate and improve the Service, as described
            in our{" "}
            <Link href="/privacy" className="underline hover:text-ink">Privacy Policy</Link>.
          </p>
        </Section>

        <Section title="7. Intellectual property">
          <p>
            The Pantry name, logo, UI design, and underlying code are our property.
            Recipes generated by the Service are provided for your personal use and
            may be shared freely — we do not claim copyright over generated meal plans.
          </p>
        </Section>

        <Section title="8. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any unlawful purpose.</li>
            <li>Attempt to reverse-engineer, scrape, or overload the Service.</li>
            <li>Resell access to the Service or its output at scale.</li>
            <li>Create multiple free accounts to circumvent tier limits.</li>
          </ul>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            Pantry provides meal suggestions and estimated costs. We are not
            nutritionists, dietitians, or financial advisors. You are responsible for
            verifying that meals suit your dietary and medical needs.
          </p>
          <p>
            To the maximum extent permitted by law, our total liability for any claim
            arising from use of the Service is limited to the amount you paid us in
            the 12 months preceding the claim, or £50, whichever is greater.
          </p>
          <p>
            Nothing in these terms excludes liability for death or personal injury
            caused by negligence, fraud, or any other liability that cannot be
            excluded under English law.
          </p>
        </Section>

        <Section title="10. Availability">
          <p>
            We aim to keep the Service available, but do not guarantee uninterrupted
            access. We may take the Service offline for maintenance with reasonable
            notice where possible.
          </p>
        </Section>

        <Section title="11. Changes to these terms">
          <p>
            We may update these terms from time to time. We will notify you of
            material changes by email or an in-app notice at least 14 days before
            they take effect. Continued use after that date constitutes acceptance.
          </p>
        </Section>

        <Section title="12. Contact">
          <p>
            Questions about these terms? Email{" "}
            <a href="mailto:hello@pantryplan.co.uk" className="underline hover:text-ink">
              hello@pantryplan.co.uk
            </a>.
          </p>
        </Section>

        <div className="mt-12 pt-6 border-t border-line flex items-center gap-4 text-sm text-muted">
          <Link href="/privacy" className="underline hover:text-ink">Privacy Policy</Link>
          <span>&middot;</span>
          <Link href="/" className="underline hover:text-ink">Back to Pantry</Link>
        </div>
      </main>
    </div>
  )
}
