"""initial schema

Revision ID: ad7f97772efe
Revises: 
Create Date: 2026-06-22 11:48:54.769748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7f97772efe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appliances_name'), 'appliances', ['name'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('calories_per_serving', sa.Integer(), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('total_cost_gbp', sa.Float(), nullable=False),
    sa.Column('cost_per_serving_gbp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index('idx_recipes_cost_calories', 'recipes', ['cost_per_serving_gbp', 'calories_per_serving'], unique=False)
    op.create_index(op.f('ix_recipes_calories_per_serving'), 'recipes', ['calories_per_serving'], unique=False)
    op.create_index(op.f('ix_recipes_cost_per_serving_gbp'), 'recipes', ['cost_per_serving_gbp'], unique=False)
    op.create_index(op.f('ix_recipes_cuisine'), 'recipes', ['cuisine'], unique=False)
    op.create_index(op.f('ix_recipes_total_cost_gbp'), 'recipes', ['total_cost_gbp'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('est_price_gbp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_table('recipe_appliances',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'appliance_id')
    )
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('recipe_tags')
    op.drop_table('recipe_appliances')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_recipes_total_cost_gbp'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_cuisine'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_cost_per_serving_gbp'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_calories_per_serving'), table_name='recipes')
    op.drop_index('idx_recipes_cost_calories', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_appliances_name'), table_name='appliances')
    op.drop_table('appliances')
    # ### end Alembic commands ###
